#!/usr/bin/env node

'use strict';

var meow = require('meow');
var indentString = require('indent-string');
var foxes = require('./');

meow([
	'Usage',
	'  $ foxes'
]);

console.log('\n\n' + indentString(foxes(), '\t') + '\n');
